### ISSUE TITLE
Opencl request.

### ISSUE THREAD

**Issue by Yorizuka** [mtanana/torchneuralconvo#1]
is there any way to get this working with a AMD GPU using opencl or something like it?

**Comment by mtanana** [comment]
Hey-  sorry for leaving you hanging for so long @minecraftlog21 !  

I think there is, but I don't have an opencl card to test it on...

anyplace where you see :cuda() if you replace it with :cl() it _may_ work...depends a bit on how much all of the libraries support openCL

If it works, will you let me know and I will make it an official supported version!

**Comment by Yorizuka** [comment]
no luck :disappointed:
