### ISSUE TITLE
Evaluation input sequence, beam search, dataset

### ISSUE THREAD

**Issue by BranaHi** [mtanana/torchneuralconvo#2]
I have multiple questions for you.

1. You are reversing the input sequence during training but i don't see you doing this with the input sequence when using eval.lua . Am I missing something?

2. You mention a beam search implementation but there seems to be no beam.lua. Could you please add it ?

3. Could you give a little bit more information about the dataset you used ? What do you mean by the first 9 milion ? And could you please share some information about the errors you achieved in the training?

Thank you!

**Comment by mtanana** [comment]
1)  Do I?  I think some earlier code that I was working off of may have done this, but if it is still this way it is a bug.  Let me know if you see that in the code and I'll fix it.  I know some papers have found this helps, but it doesn't work for all situations, and so I don't generally write this in.  
2)  A yes...you are right...pushing now!  Thanks..  Let me know if there are any inconsistencies introduced by the update.
3)  Let me see if I can find the perplexity...I have it recorded somewhere, just not sure if it is for that 9m dataset.   For the 9 million:  I took the opensubs dataset and just grabbed the first 9 million lines.

**Comment by mtanana** [comment]
Not sure I can find that exact model output anymore...here is a similar one (different vocab size, and you can't really compare across models with different vocab sizes)

minLR: 1e-05 track: 1 learningRate: 0.01 cuda: true batchSize: 1 seq_length_in: 25 dataDir: data/opensubssmall/ grad_clip: 5 seqLength: 50 hiddenSize: 1000 seq_length_out: 25 nlayers: 2 maxEpoch: 10 rmsprop: false saturateEpoch: 20  vocabSize: 30000

This one had a loss on the test set of 2.83 after 26.6 million iterations.

**Comment by BranaHi** [comment]
To 1.
In WordSplitLMMinibatchLoader.lua starting at Line 479 starting with this comment:
--fill speaker 1 from middle->start
--speaker 1 we want to go from the last word spoken backward

The Code there makes me believe that the input part of the sequence is reversed.
So either the input has to be reversed when evaluating or there.
If i understand you right, you dont believe it to be helpful in a conversational context as opposed to a translation?

To 3. 
Thank you for the numbers. I will try to see how far i can extend the training material to train it in a reasonable amount of time and share my results.... I'm just not sure what you mean by iterations, is that minibatches over multiple epochs?

**Comment by mtanana** [comment]
1)  Ahh yes, it does sound that way, but this is actually just making sure that if we have more than the sequence-in length that we use the end of the sentence rather than the beginning.   I've actually debugged that a fair bit (you can verify by uncommenting some of the debugging code that shows how the words look in the tensor)
3)  Iterations are just individual examples...so iterations/training size is number of epochs.

**Comment by mtanana** [comment]
Let me know how it goes and if you hit any bugs!
