### ISSUE TITLE
Error loading dataset

### ISSUE THREAD

**Issue by darshkotecha** [mtanana/torchneuralconvo#3]
tried running your code without cuda
stopped at 7 epoch cycles
loaded a new dataset received this error please help 
I am new to lua programming

could you please help me understand the error 

is it because of large input and output string I entered

> -- Loading dataset	
> vocab.t7 or data.t7 detected as stale. Re-running preprocessing...	
> one-time setup: preprocessing input text file data/opensubssmall/input.txt...	
> loading text file...	
> creating vocabulary mapping...	
> 1027
> Count: 385	
> Length: 1027	
> putting data into tensor...	
> /home/guru99u2/torch/install/bin/luajit: ./util/WordSplitLMMinibatchLoader.lua:529: bad argument #3 to 'narrow' (out of range at /tmp/luarocks_torch-scm-1-405/torch7/lib/TH/generic/THTensor.c:351)
> stack traceback:
> 	[C]: in function 'narrow'
> 	./util/WordSplitLMMinibatchLoader.lua:529: in function 'text_to_tensor'
> 	./util/WordSplitLMMinibatchLoader.lua:90: in function 'create'
> 	trainoptim.lua:67: in main chunk
> 	[C]: in function 'dofile'
> 	...99u2/torch/install/lib/luarocks/rocks/trepl/scm-1/bin/th:145: in main chunk
	[C]: at 0x00406670

**Comment by BranaHi** [comment]
It sounds like the amount of training data you are usings is very small.
The training/validation/test split of the data leads to a 0 size of the validation data which in turn leads to the error when splitting the data tensor into those 3 parts.

You could either increase the amount of data you use or you can make sure the code accepts 0 size validation/test data. To run with everything as trainingdata i made the following changes:

In WordSplitLMMinibatchLoader.lua

exchange Line 529/530 with:
if nval>0 then
data.val = examples:narrow(1,ntrain+1,nval)
data.test = examples:narrow(1,ntrain+nval+1,ntest)
end

and also exchange Line 110/111 with:
if self.val ~=nil then
    self.nval = math.floor(self.val:size(1)/batch_size)-1
    self.ntest = math.floor(self.test:size(1)/batch_size)-1
else
    self.nval=0
    self.ntest=0
end

In trainoptim.lua 
exchange Line 211 with:

if loader.nval>0 then
    local meanerr=runValidationSet()
end

**Comment by mtanana** [comment]
@darshkotecha  How many lines was your dataset?  I think @BranaHi  was probably right about the error...my batch size splitter might have trouble with these small datasets.   If you let me know the size, I'll test it with something smallish and see what I can do...

@BranaHi feel free to push that change too!

**Comment by darshkotecha** [comment]
I had 3 lines in the dataset. But the length of the lines was long it was a para-graphic conversation.
Thanks for your help it means a lot
made the changes you @BranaHi suggested still receiving this error

-- Loading dataset	
/home/u2/torch/install/bin/lua: ./util/WordSplitLMMinibatchLoader.lua:82: attempt to index local 'input_attr' (a nil value)
stack traceback:
	./util/WordSplitLMMinibatchLoader.lua:82: in function 'create'
	trainoptim.lua:67: in main chunk
	[C]: in function 'dofile'
	...99u2/torch/install/lib/luarocks/rocks/trepl/scm-1/bin/th:145: in main chunk
	[C]: in ?

**Comment by darshkotecha** [comment]
@BranaHi & @mtanana thanks for help
I increased my dataset size to 1000 lines and received this error after the amendment suggested by @BranaHi 
**AMMENDED CODE** ERROR 
++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++

```
-- Loading dataset  
vocab.t7 or data.t7 detected as stale. Re-running preprocessing...  
one-time setup: preprocessing input text file data/opensubssmall/input.txt...   
loading text file...    
creating vocabulary mapping...  
184195
313613
Count: 15000    
Length: 313613  
putting data into tensor... 
saving data/opensubssmall/vocabwords.t7 
saving data/opensubssmall/datawords.t7  
loading data files...   
Vocab Size15003 
/home/u2/torch/install/bin/lua: ./util/WordSplitLMMinibatchLoader.lua:120: attempt to index field 'val' (a nil value)
stack traceback:
    ./util/WordSplitLMMinibatchLoader.lua:120: in function 'create'
    trainoptim.lua:67: in main chunk
    [C]: in function 'dofile'
    ...u2/torch/install/lib/luarocks/rocks/trepl/scm-1/bin/th:145: in main chunk
    [C]: in ?
```

+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
 the case was same when i tested it with a 3 line dataset ( original dataset ) 

Also I tried to run it on original code before the edits suggested by @BranaHi  received overflow error and that was the reason of using small dataset .

the Error on **ORIGINAL Code** by @mtanana  
+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++

```
/home/u2/torch/install/bin/lua: ./util/WordSplitLMMinibatchLoader.lua:529: bad argument #3 to 'narrow' **(out of range** at /home/u2/torch/pkg/torch/lib/TH/generic/THTensor.c:360)
stack traceback:
    [C]: in function 'narrow'
    ./util/WordSplitLMMinibatchLoader.lua:529: in function 'text_to_tensor'
    ./util/WordSplitLMMinibatchLoader.lua:90: in function 'create'
    trainoptim.lua:67: in main chunk
    [C]: in function 'dofile'
    ...u2/torch/install/lib/luarocks/rocks/trepl/scm-1/bin/th:145: in main chunk
    [C]: in ?
```

**Comment by BranaHi** [comment]
@darshkotecha 
I had the feeling when writing my previous awnser that I missed one of my changes.

In Line 113(original version) and in your changed version in Line 120 there is another reference to the empty self.val variable.

print ('Val Size: ' .. self.val:size(1))

Just Comment it out or exchange self.val:size(1) with self.nval

**Comment by darshkotecha** [comment]
@BranaHi Thanks Edit Worked Perfectly & Thanks For a prompt reply

**Comment by mtanana** [comment]
Nice work!  Feel free to add a pull request and I'll commit
